name: codeverse-portal
version: 0.2.5
architectures:
  - build-on: amd64
summary: Chromium web browser in Kiosk mode on Mir
description: |
 An open-source browser project that aims to build a safer, faster, and more
 stable way for all Internet users to experience the web.
confinement: strict
grade: devel

apps:
  web-api:
    command: webserver www
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind

  chromium-mir-kiosk:
    command: desktop-launch xwayland-kiosk-launch chromium-browser.launcher
    daemon: simple
    environment:
      XWAYLAND_I3_CONFIG_FILE: $SNAP/etc/i3.config
    slots:
      - x11
    plugs:
      - browser-support
      - desktop
      - hardware-observe
      - home
      - network
      - network-manager
      - opengl
      - password-manager-service
      - removable-media
      - screen-inhibit-control
      - wayland
      - x11-plug

plugs:
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  kiosk-extension:
    source: .
    plugin: nil
    stage-packages:
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - libdb5.3

  launcher:
    plugin: dump
    source: glue
    after:
      - desktop-gtk3
      - xwayland-kiosk-helper
    organize:
      chromium-browser.launcher: bin/
      i3.config: etc/

  web-api:
    source: .
    plugin: go
    go-importpath: github.com/americademy/portal-snap

