name: codeverse-portal
version: 0.3.3
architectures:
  - build-on: amd64
summary: Codeverse Display App
description: |
  A simple remote controllable display app which runs inside the Codeverse Studios
confinement: strict
grade: stable

apps:
  web-api:
    command: webserver www
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind

  chromium-mir-kiosk:
    command: desktop-launch xwayland-kiosk-launch chromium-browser.launcher
    desktop: usr/share/applications/chromium-browser.desktop
    environment:
      CHROME_DESKTOP: chromium-browser.desktop
      XWAYLAND_I3_CONFIG_FILE: $SNAP/etc/i3.config
    plugs:
      - browser-support
      - desktop
      - hardware-observe
      - home
      - network
      - network-manager
      - opengl
      - password-manager-service
      - removable-media
      - screen-inhibit-control
      - wayland
      - x11-plug
    slots:
      - x11
      
  watcher:
    command: watcher.sh
    daemon: simple

plugs:
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11

parts:
  kiosk-extension:
    source: .
    plugin: nil
    stage-packages:
      - chromium-browser
      - chromium-codecs-ffmpeg-extra
      - libdb5.3

  launcher:
    plugin: dump
    source: glue
    after:
      - desktop-gtk3
      - xwayland-kiosk-helper
    organize:
      chromium-browser.launcher: bin/
      i3.config: etc/

  web-api:
    source: .
    plugin: go
    go-importpath: github.com/americademy/portal-snap

  watcher:
    plugin: copy
    files:
      watcher.sh: bin/

